import { Context } from "src/types";
import config from "config";

let storedKey: { access_token: string; expires_at: number } | null = null;

const getInseeKey = async (ctx: Context): Promise<string> => {
  if (!storedKey || storedKey.expires_at > Date.now() - 1000 * 60) {
    const tmp = await fetch("https://api.insee.fr/token", {
      method: "POST",
      body: "grant_type=client_credentials",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        Authorization:
          "Basic " +
          btoa(config.get("insee.key") + ":" + config.get("insee.secret")),
      },
    });
    const res = await tmp.json();
    storedKey = {
      access_token: res.access_token,
      expires_at: Date.now() + res.expires_in * 1000,
    };
  }
  return storedKey.access_token;
};

export const getSireneResult = async (
  ctx: Context,
  siret: string
): Promise<any> => {
  const key = await getInseeKey(ctx);
  const fetched = await fetch(
    // Fix me, insee changes the version of the API every weeks...
    "https://api.insee.fr/entreprises/sirene/V3.11/siret/" + siret,
    {
      headers: {
        Authorization: "Bearer " + key,
      },
    }
  );
  let tmp;
  try {
    tmp = (await fetched.json())?.etablissement;
  } catch (e) {
    console.error("Error while fetching sirene data", e, fetched);
    return {};
  }

  if (!tmp) {
    return {};
  }
  const addr = tmp.adresseEtablissement || {};
  return {
    siret: tmp.siret,
    address: {
      address_line_1: [
        addr.numeroVoieEtablissement,
        addr.indiceRepetitionEtablissement,
        addr.typeVoieEtablissement,
        addr.libelleVoieEtablissement,
      ]
        .filter(Boolean)
        .join(" "),
      address_line_2: [
        addr.codeCedexEtablissement
          ? "CEDEX " +
            addr.codeCedexEtablissement +
            " " +
            addr.libelleCedexEtablissement
          : "",
        addr.complementAdresseEtablissement,
      ]
        .filter(Boolean)
        .join(" "),
      city: addr.libelleCommuneEtablissement,
      region: "",
      country:
        sireneCountryMap.find(
          (a) => a.COG === addr.codePaysEtrangerEtablissement
        )?.CODEISO2 || "FR",
      zip: addr.codePostalEtablissement,
    },
    name: tmp.uniteLegale?.denominationUniteLegale,
  };
};

const sireneCountryMap = [
  {
    COG: 99100,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "France",
    LIBENR: "République française",
    CODEISO2: "FR",
    CODEISO3: "FRA",
    CODENUM3: 250,
  },
  {
    COG: 99101,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Danemark",
    LIBENR: "Royaume du Danemark",
    CODEISO2: "DK",
    CODEISO3: "DNK",
    CODENUM3: 208,
  },
  {
    COG: 99102,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Islande",
    LIBENR: "Islande",
    CODEISO2: "IS",
    CODEISO3: "ISL",
    CODENUM3: 352,
  },
  {
    COG: 99103,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Norvège",
    LIBENR: "Royaume de Norvège",
    CODEISO2: "NO",
    CODEISO3: "NOR",
    CODENUM3: 578,
  },
  {
    COG: 99104,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Suède",
    LIBENR: "Royaume de Suède",
    CODEISO2: "SE",
    CODEISO3: "SWE",
    CODENUM3: 752,
  },
  {
    COG: 99105,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Finlande",
    LIBENR: "République de Finlande",
    CODEISO2: "FI",
    CODEISO3: "FIN",
    CODENUM3: 246,
  },
  {
    COG: 99106,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Estonie",
    LIBENR: "République d'Estonie",
    CODEISO2: "EE",
    CODEISO3: "EST",
    CODENUM3: 233,
  },
  {
    COG: 99107,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Lettonie",
    LIBENR: "République de Lettonie",
    CODEISO2: "LV",
    CODEISO3: "LVA",
    CODENUM3: 428,
  },
  {
    COG: 99108,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1990,
    LIBCOG: "Lituanie",
    LIBENR: "République de Lituanie",
    CODEISO2: "LT",
    CODEISO3: "LTU",
    CODENUM3: 440,
  },
  {
    COG: 99109,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1990,
    LIBCOG: "Allemagne",
    LIBENR: "République fédérale d'Allemagne",
    CODEISO2: "DE",
    CODEISO3: "DEU",
    CODENUM3: 276,
  },
  {
    COG: 99110,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Autriche",
    LIBENR: "République d'Autriche",
    CODEISO2: "AT",
    CODEISO3: "AUT",
    CODENUM3: "040",
  },
  {
    COG: 99111,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Bulgarie",
    LIBENR: "République de Bulgarie",
    CODEISO2: "BG",
    CODEISO3: "BGR",
    CODENUM3: 100,
  },
  {
    COG: 99112,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Hongrie",
    LIBENR: "Hongrie",
    CODEISO2: "HU",
    CODEISO3: "HUN",
    CODENUM3: 348,
  },
  {
    COG: 99113,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Liechtenstein",
    LIBENR: "Principauté du Liechtenstein",
    CODEISO2: "LI",
    CODEISO3: "LIE",
    CODENUM3: 438,
  },
  {
    COG: 99114,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Roumanie",
    LIBENR: "Roumanie",
    CODEISO2: "RO",
    CODEISO3: "ROU",
    CODENUM3: 642,
  },
  {
    COG: 99116,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1993,
    LIBCOG: "Tchéquie",
    LIBENR: "République tchèque",
    CODEISO2: "CZ",
    CODEISO3: "CZE",
    CODENUM3: 203,
  },
  {
    COG: 99117,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1993,
    LIBCOG: "Slovaquie",
    LIBENR: "République slovaque",
    CODEISO2: "SK",
    CODEISO3: "SVK",
    CODENUM3: 703,
  },
  {
    COG: 99118,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1992,
    LIBCOG: "Bosnie-Herzégovine",
    LIBENR: "Bosnie-Herzégovine",
    CODEISO2: "BA",
    CODEISO3: "BIH",
    CODENUM3: "070",
  },
  {
    COG: 99119,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Croatie",
    LIBENR: "République de Croatie",
    CODEISO2: "HR",
    CODEISO3: "HRV",
    CODENUM3: 191,
  },
  {
    COG: 99120,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 2006,
    LIBCOG: "Monténégro",
    LIBENR: "Monténégro",
    CODEISO2: "ME",
    CODEISO3: "MNE",
    CODENUM3: 499,
  },
  {
    COG: 99121,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Serbie",
    LIBENR: "République de Serbie",
    CODEISO2: "RS",
    CODEISO3: "SRB",
    CODENUM3: 688,
  },
  {
    COG: 99122,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Pologne",
    LIBENR: "République de Pologne",
    CODEISO2: "PL",
    CODEISO3: "POL",
    CODENUM3: 616,
  },
  {
    COG: 99123,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Russie",
    LIBENR: "Fédération de Russie",
    CODEISO2: "RU",
    CODEISO3: "RUS",
    CODENUM3: 643,
  },
  {
    COG: 99125,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Albanie",
    LIBENR: "République d'Albanie",
    CODEISO2: "AL",
    CODEISO3: "ALB",
    CODENUM3: "008",
  },
  {
    COG: 99126,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Grèce",
    LIBENR: "République hellénique",
    CODEISO2: "GR",
    CODEISO3: "GRC",
    CODENUM3: 300,
  },
  {
    COG: 99127,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Italie",
    LIBENR: "République italienne",
    CODEISO2: "IT",
    CODEISO3: "ITA",
    CODENUM3: 380,
  },
  {
    COG: 99128,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Saint-Marin",
    LIBENR: "République de Saint-Marin",
    CODEISO2: "SM",
    CODEISO3: "SMR",
    CODENUM3: 674,
  },
  {
    COG: 99129,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Vatican",
    LIBENR: "Saint-Siège ou Vatican",
    CODEISO2: "VA",
    CODEISO3: "VAT",
    CODENUM3: 336,
  },
  {
    COG: 99130,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Andorre",
    LIBENR: "Principauté d'Andorre",
    CODEISO2: "AD",
    CODEISO3: "AND",
    CODENUM3: "020",
  },
  {
    COG: 99131,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Belgique",
    LIBENR: "Royaume de Belgique",
    CODEISO2: "BE",
    CODEISO3: "BEL",
    CODENUM3: "056",
  },
  {
    COG: 99132,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Royaume-Uni",
    LIBENR: "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord",
    CODEISO2: "GB",
    CODEISO3: "GBR",
    CODENUM3: 826,
  },
  {
    COG: 99133,
    ACTUAL: 4,
    CRPAY: 99132,
    ANI: "",
    LIBCOG: "Territoires britanniques en Méditerranée",
    LIBENR: "Gibraltar , Akrotiri , Dhekelia",
    CODEISO2: "GI",
    CODEISO3: "GIB",
    CODENUM3: 292,
  },
  {
    COG: 99134,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Espagne",
    LIBENR: "Royaume d'Espagne",
    CODEISO2: "ES",
    CODEISO3: "ESP",
    CODENUM3: 724,
  },
  {
    COG: 99135,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Pays-Bas",
    LIBENR: "Royaume des Pays-Bas",
    CODEISO2: "NL",
    CODEISO3: "NLD",
    CODENUM3: 528,
  },
  {
    COG: 99136,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Irlande",
    LIBENR: "Irlande",
    CODEISO2: "IE",
    CODEISO3: "IRL",
    CODENUM3: 372,
  },
  {
    COG: 99137,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Luxembourg",
    LIBENR: "Grand-Duché du Luxembourg",
    CODEISO2: "LU",
    CODEISO3: "LUX",
    CODENUM3: 442,
  },
  {
    COG: 99138,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Monaco",
    LIBENR: "Principauté de Monaco",
    CODEISO2: "MC",
    CODEISO3: "MCO",
    CODENUM3: 492,
  },
  {
    COG: 99139,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Portugal",
    LIBENR: "République portugaise",
    CODEISO2: "PT",
    CODEISO3: "PRT",
    CODENUM3: 620,
  },
  {
    COG: 99140,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Suisse",
    LIBENR: "Confédération suisse",
    CODEISO2: "CH",
    CODEISO3: "CHE",
    CODENUM3: 756,
  },
  {
    COG: 99144,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1964,
    LIBCOG: "Malte",
    LIBENR: "République de Malte",
    CODEISO2: "MT",
    CODEISO3: "MLT",
    CODENUM3: 470,
  },
  {
    COG: 99145,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Slovénie",
    LIBENR: "République de Slovénie",
    CODEISO2: "SI",
    CODEISO3: "SVN",
    CODENUM3: 705,
  },
  {
    COG: 99148,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Biélorussie",
    LIBENR: "République de Biélorussie",
    CODEISO2: "BY",
    CODEISO3: "BLR",
    CODENUM3: 112,
  },
  {
    COG: 99151,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Moldavie",
    LIBENR: "République de Moldavie",
    CODEISO2: "MD",
    CODEISO3: "MDA",
    CODENUM3: 498,
  },
  {
    COG: 99155,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Ukraine",
    LIBENR: "Ukraine",
    CODEISO2: "UA",
    CODEISO3: "UKR",
    CODENUM3: 804,
  },
  {
    COG: 99156,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Macédoine du Nord",
    LIBENR: "République de Macédoine du Nord",
    CODEISO2: "MK",
    CODEISO3: "MKD",
    CODENUM3: 807,
  },
  {
    COG: 99157,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 2007,
    LIBCOG: "Kosovo",
    LIBENR: "République du Kosovo",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99158,
    ACTUAL: 4,
    CRPAY: 99101,
    ANI: "",
    LIBCOG: "Féroé",
    LIBENR: "Îles Féroé",
    CODEISO2: "FO",
    CODEISO3: "FRO",
    CODENUM3: 234,
  },
  {
    COG: 99159,
    ACTUAL: 4,
    CRPAY: 99103,
    ANI: "",
    LIBCOG: "Territoires norvégiens en Atlantique Nord",
    LIBENR: "Île Jan-Mayen , Svalbard",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99160,
    ACTUAL: 4,
    CRPAY: 99105,
    ANI: "",
    LIBCOG: "Åland",
    LIBENR: "Îles Åland",
    CODEISO2: "AX",
    CODEISO3: "ALA",
    CODENUM3: 248,
  },
  {
    COG: 99161,
    ACTUAL: 4,
    CRPAY: 99132,
    ANI: "",
    LIBCOG: "Dépendances de la Couronne britannique",
    LIBENR: "Île de Man , Jersey , Guernesey",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99201,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Arabie saoudite",
    LIBENR: "Royaume d'Arabie saoudite",
    CODEISO2: "SA",
    CODEISO3: "SAU",
    CODENUM3: 682,
  },
  {
    COG: 99203,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Irak",
    LIBENR: "République d'Irak",
    CODEISO2: "IQ",
    CODEISO3: "IRQ",
    CODENUM3: 368,
  },
  {
    COG: 99204,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Iran",
    LIBENR: "République islamique d'Iran",
    CODEISO2: "IR",
    CODEISO3: "IRN",
    CODENUM3: 364,
  },
  {
    COG: 99205,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Liban",
    LIBENR: "République libanaise",
    CODEISO2: "LB",
    CODEISO3: "LBN",
    CODENUM3: 422,
  },
  {
    COG: 99206,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1961,
    LIBCOG: "Syrie",
    LIBENR: "République arabe syrienne",
    CODEISO2: "SY",
    CODEISO3: "SYR",
    CODENUM3: 760,
  },
  {
    COG: 99207,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Israël",
    LIBENR: "État d'Israël",
    CODEISO2: "IL",
    CODEISO3: "ISR",
    CODENUM3: 376,
  },
  {
    COG: 99208,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Turquie",
    LIBENR: "République de Turquie",
    CODEISO2: "TR",
    CODEISO3: "TUR",
    CODENUM3: 792,
  },
  {
    COG: 99212,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Afghanistan",
    LIBENR: "République islamique d'Afghanistan",
    CODEISO2: "AF",
    CODEISO3: "AFG",
    CODENUM3: "004",
  },
  {
    COG: 99213,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Pakistan",
    LIBENR: "République islamique du Pakistan",
    CODEISO2: "PK",
    CODEISO3: "PAK",
    CODENUM3: 586,
  },
  {
    COG: 99214,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1949,
    LIBCOG: "Bhoutan",
    LIBENR: "Royaume du Bhoutan",
    CODEISO2: "BT",
    CODEISO3: "BTN",
    CODENUM3: "064",
  },
  {
    COG: 99215,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Népal",
    LIBENR: "Népal",
    CODEISO2: "NP",
    CODEISO3: "NPL",
    CODENUM3: 524,
  },
  {
    COG: 99216,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Chine",
    LIBENR: "République populaire de Chine",
    CODEISO2: "CN",
    CODEISO3: "CHN",
    CODENUM3: 156,
  },
  {
    COG: 99217,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Japon",
    LIBENR: "Japon",
    CODEISO2: "JP",
    CODEISO3: "JPN",
    CODENUM3: 392,
  },
  {
    COG: 99219,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Thaïlande",
    LIBENR: "Royaume de Thaïlande",
    CODEISO2: "TH",
    CODEISO3: "THA",
    CODENUM3: 764,
  },
  {
    COG: 99220,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Philippines",
    LIBENR: "République des Philippines",
    CODEISO2: "PH",
    CODEISO3: "PHL",
    CODENUM3: 608,
  },
  {
    COG: 99222,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Jordanie",
    LIBENR: "Royaume hachémite de Jordanie",
    CODEISO2: "JO",
    CODEISO3: "JOR",
    CODENUM3: 400,
  },
  {
    COG: 99223,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Inde",
    LIBENR: "République de l'Inde",
    CODEISO2: "IN",
    CODEISO3: "IND",
    CODENUM3: 356,
  },
  {
    COG: 99224,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Birmanie",
    LIBENR: "République de l'Union de Birmanie",
    CODEISO2: "MM",
    CODEISO3: "MMR",
    CODENUM3: 104,
  },
  {
    COG: 99225,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Brunei",
    LIBENR: "Brunei Darussalam",
    CODEISO2: "BN",
    CODEISO3: "BRN",
    CODENUM3: "096",
  },
  {
    COG: 99226,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1965,
    LIBCOG: "Singapour",
    LIBENR: "République de Singapour",
    CODEISO2: "SG",
    CODEISO3: "SGP",
    CODENUM3: 702,
  },
  {
    COG: 99227,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Malaisie",
    LIBENR: "Malaisie",
    CODEISO2: "MY",
    CODEISO3: "MYS",
    CODENUM3: 458,
  },
  {
    COG: 99229,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Maldives",
    LIBENR: "République des Maldives",
    CODEISO2: "MV",
    CODEISO3: "MDV",
    CODENUM3: 462,
  },
  {
    COG: 99230,
    ACTUAL: 4,
    CRPAY: 99216,
    ANI: "",
    LIBCOG: "Hong Kong",
    LIBENR: "Hong Kong",
    CODEISO2: "HK",
    CODEISO3: "HKG",
    CODENUM3: 344,
  },
  {
    COG: 99231,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Indonésie",
    LIBENR: "République d'Indonésie",
    CODEISO2: "ID",
    CODEISO3: "IDN",
    CODENUM3: 360,
  },
  {
    COG: 99232,
    ACTUAL: 4,
    CRPAY: 99216,
    ANI: "",
    LIBCOG: "Macao",
    LIBENR: "Macao",
    CODEISO2: "MO",
    CODEISO3: "MAC",
    CODENUM3: 446,
  },
  {
    COG: 99234,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1953,
    LIBCOG: "Cambodge",
    LIBENR: "Royaume du Cambodge",
    CODEISO2: "KH",
    CODEISO3: "KHM",
    CODENUM3: 116,
  },
  {
    COG: 99235,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Sri Lanka",
    LIBENR: "République démocratique socialiste du Sri Lanka",
    CODEISO2: "LK",
    CODEISO3: "LKA",
    CODENUM3: 144,
  },
  {
    COG: 99236,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1949,
    LIBCOG: "Taïwan",
    LIBENR: "Taïwan",
    CODEISO2: "TW",
    CODEISO3: "TWN",
    CODENUM3: 158,
  },
  {
    COG: 99238,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1953,
    LIBCOG: "Corée du Nord",
    LIBENR: "République populaire démocratique de Corée",
    CODEISO2: "KP",
    CODEISO3: "PRK",
    CODENUM3: 408,
  },
  {
    COG: 99239,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1953,
    LIBCOG: "Corée du Sud",
    LIBENR: "République de Corée",
    CODEISO2: "KR",
    CODEISO3: "KOR",
    CODENUM3: 410,
  },
  {
    COG: 99240,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1961,
    LIBCOG: "Koweït",
    LIBENR: "État du Koweït",
    CODEISO2: "KW",
    CODEISO3: "KWT",
    CODENUM3: 414,
  },
  {
    COG: 99241,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1953,
    LIBCOG: "Laos",
    LIBENR: "République démocratique populaire lao",
    CODEISO2: "LA",
    CODEISO3: "LAO",
    CODENUM3: 418,
  },
  {
    COG: 99242,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1945,
    LIBCOG: "Mongolie",
    LIBENR: "Mongolie",
    CODEISO2: "MN",
    CODEISO3: "MNG",
    CODENUM3: 496,
  },
  {
    COG: 99243,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1976,
    LIBCOG: "Vietnam",
    LIBENR: "République socialiste du Vietnam",
    CODEISO2: "VN",
    CODEISO3: "VNM",
    CODENUM3: 704,
  },
  {
    COG: 99246,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1971,
    LIBCOG: "Bangladesh",
    LIBENR: "République populaire du Bangladesh",
    CODEISO2: "BD",
    CODEISO3: "BGD",
    CODENUM3: "050",
  },
  {
    COG: 99247,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1971,
    LIBCOG: "Émirats arabes unis",
    LIBENR: "Émirats arabes unis",
    CODEISO2: "AE",
    CODEISO3: "ARE",
    CODENUM3: 784,
  },
  {
    COG: 99248,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1971,
    LIBCOG: "Qatar",
    LIBENR: "État du Qatar",
    CODEISO2: "QA",
    CODEISO3: "QAT",
    CODENUM3: 634,
  },
  {
    COG: 99249,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1971,
    LIBCOG: "Bahreïn",
    LIBENR: "Royaume de Bahreïn",
    CODEISO2: "BH",
    CODEISO3: "BHR",
    CODENUM3: "048",
  },
  {
    COG: 99250,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1970,
    LIBCOG: "Oman",
    LIBENR: "Sultanat d'Oman",
    CODEISO2: "OM",
    CODEISO3: "OMN",
    CODENUM3: 512,
  },
  {
    COG: 99251,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1990,
    LIBCOG: "Yémen",
    LIBENR: "République du Yémen",
    CODEISO2: "YE",
    CODEISO3: "YEM",
    CODENUM3: 887,
  },
  {
    COG: 99252,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Arménie",
    LIBENR: "République d'Arménie",
    CODEISO2: "AM",
    CODEISO3: "ARM",
    CODENUM3: "051",
  },
  {
    COG: 99253,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Azerbaïdjan",
    LIBENR: "République d'Azerbaïdjan",
    CODEISO2: "AZ",
    CODEISO3: "AZE",
    CODENUM3: "031",
  },
  {
    COG: 99254,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1994,
    LIBCOG: "Chypre",
    LIBENR: "République de Chypre",
    CODEISO2: "CY",
    CODEISO3: "CYP",
    CODENUM3: 196,
  },
  {
    COG: 99255,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Géorgie",
    LIBENR: "Géorgie",
    CODEISO2: "GE",
    CODEISO3: "GEO",
    CODENUM3: 268,
  },
  {
    COG: 99256,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Kazakhstan",
    LIBENR: "République du Kazakhstan",
    CODEISO2: "KZ",
    CODEISO3: "KAZ",
    CODENUM3: 398,
  },
  {
    COG: 99257,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Kirghizstan",
    LIBENR: "République kirghize",
    CODEISO2: "KG",
    CODEISO3: "KGZ",
    CODENUM3: 417,
  },
  {
    COG: 99258,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Ouzbékistan",
    LIBENR: "République d'Ouzbékistan",
    CODEISO2: "UZ",
    CODEISO3: "UZB",
    CODENUM3: 860,
  },
  {
    COG: 99259,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Tadjikistan",
    LIBENR: "République du Tadjikistan",
    CODEISO2: "TJ",
    CODEISO3: "TJK",
    CODENUM3: 762,
  },
  {
    COG: 99260,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1991,
    LIBCOG: "Turkménistan",
    LIBENR: "Turkménistan",
    CODEISO2: "TM",
    CODEISO3: "TKM",
    CODENUM3: 795,
  },
  {
    COG: 99261,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1948,
    LIBCOG: "Palestine",
    LIBENR: "État de Palestine",
    CODEISO2: "PS",
    CODEISO3: "PSE",
    CODENUM3: 275,
  },
  {
    COG: 99262,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 2002,
    LIBCOG: "Timor oriental",
    LIBENR: "République démocratique du Timor oriental",
    CODEISO2: "TL",
    CODEISO3: "TLS",
    CODENUM3: 626,
  },
  {
    COG: 99265,
    ACTUAL: 4,
    CRPAY: 99501,
    ANI: "",
    LIBCOG: "Territoires australiens de l’océan Indien",
    LIBENR:
      "Îles Ashmore-et-Cartier , territoire antarctique australien , îles Heard-et-MacDonald , îles Cocos , île Christmas",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99301,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Égypte",
    LIBENR: "République arabe d'Égypte",
    CODEISO2: "EG",
    CODEISO3: "EGY",
    CODENUM3: 818,
  },
  {
    COG: 99302,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Libéria",
    LIBENR: "République du Libéria",
    CODEISO2: "LR",
    CODEISO3: "LBR",
    CODENUM3: 430,
  },
  {
    COG: 99303,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Afrique du Sud",
    LIBENR: "République d'Afrique du Sud",
    CODEISO2: "ZA",
    CODEISO3: "ZAF",
    CODENUM3: 710,
  },
  {
    COG: 99304,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Gambie",
    LIBENR: "République de Gambie",
    CODEISO2: "GM",
    CODEISO3: "GMB",
    CODENUM3: 270,
  },
  {
    COG: 99306,
    ACTUAL: 4,
    CRPAY: 99132,
    ANI: "",
    LIBCOG: "Territoires britanniques de l’océan Atlantique",
    LIBENR: "Îles Sainte-Hélène, Ascension, Tristan-da-Cunha",
    CODEISO2: "SH",
    CODEISO3: "SHN",
    CODENUM3: 654,
  },
  {
    COG: 99308,
    ACTUAL: 4,
    CRPAY: 99132,
    ANI: "",
    LIBCOG: "Chagos",
    LIBENR: "Îles Chagos",
    CODEISO2: "IO",
    CODEISO3: "IOT",
    CODENUM3: "086",
  },
  {
    COG: 99309,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Tanzanie",
    LIBENR: "République unie de Tanzanie",
    CODEISO2: "TZ",
    CODEISO3: "TZA",
    CODENUM3: 834,
  },
  {
    COG: 99310,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Zimbabwe",
    LIBENR: "République du Zimbabwe",
    CODEISO2: "ZW",
    CODEISO3: "ZWE",
    CODENUM3: 716,
  },
  {
    COG: 99311,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Namibie",
    LIBENR: "République de Namibie",
    CODEISO2: "NA",
    CODEISO3: "NAM",
    CODENUM3: 516,
  },
  {
    COG: 99312,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "République démocratique du Congo",
    LIBENR: "République démocratique du Congo",
    CODEISO2: "CD",
    CODEISO3: "COD",
    CODENUM3: 180,
  },
  {
    COG: 99313,
    ACTUAL: 4,
    CRPAY: 99134,
    ANI: "",
    LIBCOG: "Territoires espagnols en Afrique du Nord",
    LIBENR: "Ceuta , Melilla , Présides , îles Canaries",
    CODEISO2: "ES",
    CODEISO3: "ESP",
    CODENUM3: 724,
  },
  {
    COG: 99314,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Guinée équatoriale",
    LIBENR: "République de Guinée équatoriale",
    CODEISO2: "GQ",
    CODEISO3: "GNQ",
    CODENUM3: 226,
  },
  {
    COG: 99315,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Éthiopie",
    LIBENR: "République démocratique fédérale d'Éthiopie",
    CODEISO2: "ET",
    CODEISO3: "ETH",
    CODENUM3: 231,
  },
  {
    COG: 99316,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Libye",
    LIBENR: "État de Libye",
    CODEISO2: "LY",
    CODEISO3: "LBY",
    CODENUM3: 434,
  },
  {
    COG: 99317,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1993,
    LIBCOG: "Érythrée",
    LIBENR: "État d'Érythrée",
    CODEISO2: "ER",
    CODEISO3: "ERI",
    CODENUM3: 232,
  },
  {
    COG: 99318,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Somalie",
    LIBENR: "République fédérale de Somalie",
    CODEISO2: "SO",
    CODEISO3: "SOM",
    CODENUM3: 706,
  },
  {
    COG: 99319,
    ACTUAL: 4,
    CRPAY: 99139,
    ANI: "",
    LIBCOG: "Territoires portugais de l’océan Atlantique",
    LIBENR: "Açores , Madère",
    CODEISO2: "PT",
    CODEISO3: "PRT",
    CODENUM3: 620,
  },
  {
    COG: 99321,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Burundi",
    LIBENR: "République du Burundi",
    CODEISO2: "BI",
    CODEISO3: "BDI",
    CODENUM3: 108,
  },
  {
    COG: 99322,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1961,
    LIBCOG: "Cameroun",
    LIBENR: "République du Cameroun",
    CODEISO2: "CM",
    CODEISO3: "CMR",
    CODENUM3: 120,
  },
  {
    COG: 99323,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Centrafrique",
    LIBENR: "République centrafricaine",
    CODEISO2: "CF",
    CODEISO3: "CAF",
    CODENUM3: 140,
  },
  {
    COG: 99324,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Congo",
    LIBENR: "République du Congo",
    CODEISO2: "CD",
    CODEISO3: "COD",
    CODENUM3: 180,
  },
  {
    COG: 99326,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Côte d’Ivoire",
    LIBENR: "République de Côte d'Ivoire",
    CODEISO2: "CI",
    CODEISO3: "CIV",
    CODENUM3: 384,
  },
  {
    COG: 99327,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Bénin",
    LIBENR: "République du Bénin",
    CODEISO2: "BJ",
    CODEISO3: "BEN",
    CODENUM3: 204,
  },
  {
    COG: 99328,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Gabon",
    LIBENR: "République gabonaise",
    CODEISO2: "GA",
    CODEISO3: "GAB",
    CODENUM3: 266,
  },
  {
    COG: 99329,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1957,
    LIBCOG: "Ghana",
    LIBENR: "République du Ghana",
    CODEISO2: "GH",
    CODEISO3: "GHA",
    CODENUM3: 288,
  },
  {
    COG: 99330,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1958,
    LIBCOG: "Guinée",
    LIBENR: "République de Guinée",
    CODEISO2: "GN",
    CODEISO3: "GIN",
    CODENUM3: 324,
  },
  {
    COG: 99331,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Burkina",
    LIBENR: "Burkina Faso",
    CODEISO2: "BF",
    CODEISO3: "BFA",
    CODENUM3: 854,
  },
  {
    COG: 99332,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1963,
    LIBCOG: "Kenya",
    LIBENR: "République du Kenya",
    CODEISO2: "KE",
    CODEISO3: "KEN",
    CODENUM3: 404,
  },
  {
    COG: 99333,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Madagascar",
    LIBENR: "République de Madagascar",
    CODEISO2: "MG",
    CODEISO3: "MDG",
    CODENUM3: 450,
  },
  {
    COG: 99334,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1964,
    LIBCOG: "Malawi",
    LIBENR: "République du Malawi",
    CODEISO2: "MW",
    CODEISO3: "MWI",
    CODENUM3: 454,
  },
  {
    COG: 99335,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Mali",
    LIBENR: "République du Mali",
    CODEISO2: "ML",
    CODEISO3: "MLI",
    CODENUM3: 466,
  },
  {
    COG: 99336,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Mauritanie",
    LIBENR: "République islamique de Mauritanie",
    CODEISO2: "MR",
    CODEISO3: "MRT",
    CODENUM3: 478,
  },
  {
    COG: 99337,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Niger",
    LIBENR: "République du Niger",
    CODEISO2: "NE",
    CODEISO3: "NER",
    CODENUM3: 562,
  },
  {
    COG: 99338,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Nigéria",
    LIBENR: "République fédérale du Nigéria",
    CODEISO2: "NG",
    CODEISO3: "NGA",
    CODENUM3: 566,
  },
  {
    COG: 99339,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1962,
    LIBCOG: "Ouganda",
    LIBENR: "République d'Ouganda",
    CODEISO2: "UG",
    CODEISO3: "UGA",
    CODENUM3: 800,
  },
  {
    COG: 99340,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1962,
    LIBCOG: "Rwanda",
    LIBENR: "République du Rwanda",
    CODEISO2: "RW",
    CODEISO3: "RWA",
    CODENUM3: 646,
  },
  {
    COG: 99341,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Sénégal",
    LIBENR: "République du Sénégal",
    CODEISO2: "SN",
    CODEISO3: "SEN",
    CODENUM3: 686,
  },
  {
    COG: 99342,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1961,
    LIBCOG: "Sierra Leone",
    LIBENR: "République de Sierra Leone",
    CODEISO2: "SL",
    CODEISO3: "SLE",
    CODENUM3: 694,
  },
  {
    COG: 99343,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1956,
    LIBCOG: "Soudan",
    LIBENR: "République du Soudan",
    CODEISO2: "SD",
    CODEISO3: "SDN",
    CODENUM3: 729,
  },
  {
    COG: 99344,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Tchad",
    LIBENR: "République du Tchad",
    CODEISO2: "TD",
    CODEISO3: "TCD",
    CODENUM3: 148,
  },
  {
    COG: 99345,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1960,
    LIBCOG: "Togo",
    LIBENR: "République togolaise",
    CODEISO2: "TG",
    CODEISO3: "TGO",
    CODENUM3: 768,
  },
  {
    COG: 99346,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1964,
    LIBCOG: "Zambie",
    LIBENR: "République de Zambie",
    CODEISO2: "ZM",
    CODEISO3: "ZMB",
    CODENUM3: 894,
  },
  {
    COG: 99347,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1966,
    LIBCOG: "Botswana",
    LIBENR: "République du Botswana",
    CODEISO2: "BW",
    CODEISO3: "BWA",
    CODENUM3: "072",
  },
  {
    COG: 99348,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1966,
    LIBCOG: "Lesotho",
    LIBENR: "Royaume du Lesotho",
    CODEISO2: "LS",
    CODEISO3: "LSO",
    CODENUM3: 426,
  },
  {
    COG: 99349,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 2011,
    LIBCOG: "Soudan du Sud",
    LIBENR: "République du Soudan du Sud",
    CODEISO2: "SS",
    CODEISO3: "SSD",
    CODENUM3: 728,
  },
  {
    COG: 99350,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1956,
    LIBCOG: "Maroc",
    LIBENR: "Royaume du Maroc",
    CODEISO2: "MA",
    CODEISO3: "MAR",
    CODENUM3: 504,
  },
  {
    COG: 99351,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1956,
    LIBCOG: "Tunisie",
    LIBENR: "République tunisienne",
    CODEISO2: "TN",
    CODEISO3: "TUN",
    CODENUM3: 788,
  },
  {
    COG: 99352,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1962,
    LIBCOG: "Algérie",
    LIBENR: "République algérienne démocratique et populaire",
    CODEISO2: "DZ",
    CODEISO3: "DZA",
    CODENUM3: "012",
  },
  {
    COG: 99363,
    ACTUAL: 4,
    CRPAY: 99103,
    ANI: "",
    LIBCOG: "Terres australes norvégiennes",
    LIBENR: "Île Bouvet , île Pierre-Ier , terre de la Reine-Maud",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99389,
    ACTUAL: 4,
    CRPAY: "",
    ANI: 1994,
    LIBCOG: "Sahara occidental",
    LIBENR: "Sahara occidental",
    CODEISO2: "EH",
    CODEISO3: "ESH",
    CODENUM3: 732,
  },
  {
    COG: 99390,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1968,
    LIBCOG: "Maurice",
    LIBENR: "République de Maurice",
    CODEISO2: "MU",
    CODEISO3: "MUS",
    CODENUM3: 480,
  },
  {
    COG: 99391,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1968,
    LIBCOG: "Swaziland",
    LIBENR: "Royaume du Swaziland",
    CODEISO2: "SZ",
    CODEISO3: "SWZ",
    CODENUM3: 748,
  },
  {
    COG: 99392,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1974,
    LIBCOG: "Guinée-Bissao",
    LIBENR: "République de Guinée-Bissao",
    CODEISO2: "GW",
    CODEISO3: "GNB",
    CODENUM3: 624,
  },
  {
    COG: 99393,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1975,
    LIBCOG: "Mozambique",
    LIBENR: "République du Mozambique",
    CODEISO2: "MZ",
    CODEISO3: "MOZ",
    CODENUM3: 508,
  },
  {
    COG: 99394,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1975,
    LIBCOG: "Sao Tomé-et-Principe",
    LIBENR: "République démocratique de Sao Tomé-et-Principe",
    CODEISO2: "ST",
    CODEISO3: "STP",
    CODENUM3: 678,
  },
  {
    COG: 99395,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1975,
    LIBCOG: "Angola",
    LIBENR: "République d'Angola",
    CODEISO2: "AO",
    CODEISO3: "AGO",
    CODENUM3: "024",
  },
  {
    COG: 99396,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1975,
    LIBCOG: "Cap-Vert",
    LIBENR: "République du Cap-Vert",
    CODEISO2: "CV",
    CODEISO3: "CPV",
    CODENUM3: 132,
  },
  {
    COG: 99397,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1975,
    LIBCOG: "Comores",
    LIBENR: "Union des Comores",
    CODEISO2: "KM",
    CODEISO3: "COM",
    CODENUM3: 174,
  },
  {
    COG: 99398,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1976,
    LIBCOG: "Seychelles",
    LIBENR: "République des Seychelles",
    CODEISO2: "SC",
    CODEISO3: "SYC",
    CODENUM3: 690,
  },
  {
    COG: 99399,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1977,
    LIBCOG: "Djibouti",
    LIBENR: "République de Djibouti",
    CODEISO2: "DJ",
    CODEISO3: "DJI",
    CODENUM3: 262,
  },
  {
    COG: 99401,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Canada",
    LIBENR: "Canada",
    CODEISO2: "CA",
    CODEISO3: "CAN",
    CODENUM3: 124,
  },
  {
    COG: 99404,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "États-Unis",
    LIBENR: "États-Unis d'Amérique",
    CODEISO2: "US",
    CODEISO3: "USA",
    CODENUM3: 840,
  },
  {
    COG: 99405,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Mexique",
    LIBENR: "États-Unis du Mexique",
    CODEISO2: "MX",
    CODEISO3: "MEX",
    CODENUM3: 484,
  },
  {
    COG: 99406,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Costa Rica",
    LIBENR: "République du Costa Rica",
    CODEISO2: "CR",
    CODEISO3: "CRI",
    CODENUM3: 188,
  },
  {
    COG: 99407,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Cuba",
    LIBENR: "République de Cuba",
    CODEISO2: "CU",
    CODEISO3: "CUB",
    CODENUM3: 192,
  },
  {
    COG: 99408,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "République dominicaine",
    LIBENR: "République dominicaine",
    CODEISO2: "DO",
    CODEISO3: "DOM",
    CODENUM3: 214,
  },
  {
    COG: 99409,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Guatemala",
    LIBENR: "République du Guatemala",
    CODEISO2: "GT",
    CODEISO3: "GTM",
    CODENUM3: 320,
  },
  {
    COG: 99410,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Haïti",
    LIBENR: "République d'Haïti",
    CODEISO2: "HT",
    CODEISO3: "HTI",
    CODENUM3: 332,
  },
  {
    COG: 99411,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Honduras",
    LIBENR: "République du Honduras",
    CODEISO2: "HN",
    CODEISO3: "HND",
    CODENUM3: 340,
  },
  {
    COG: 99412,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Nicaragua",
    LIBENR: "République du Nicaragua",
    CODEISO2: "NI",
    CODEISO3: "NIC",
    CODENUM3: 558,
  },
  {
    COG: 99413,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Panama",
    LIBENR: "République du Panama",
    CODEISO2: "PA",
    CODEISO3: "PAN",
    CODENUM3: 591,
  },
  {
    COG: 99414,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Salvador",
    LIBENR: "République du Salvador",
    CODEISO2: "SV",
    CODEISO3: "SLV",
    CODENUM3: 222,
  },
  {
    COG: 99415,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Argentine",
    LIBENR: "République argentine",
    CODEISO2: "AR",
    CODEISO3: "ARG",
    CODENUM3: "032",
  },
  {
    COG: 99416,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Brésil",
    LIBENR: "République fédérative du Brésil",
    CODEISO2: "BR",
    CODEISO3: "BRA",
    CODENUM3: "076",
  },
  {
    COG: 99417,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Chili",
    LIBENR: "République du Chili",
    CODEISO2: "CL",
    CODEISO3: "CHL",
    CODENUM3: 152,
  },
  {
    COG: 99418,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Bolivie",
    LIBENR: "État plurinational de Bolivie",
    CODEISO2: "BO",
    CODEISO3: "BOL",
    CODENUM3: "068",
  },
  {
    COG: 99419,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Colombie",
    LIBENR: "République de Colombie",
    CODEISO2: "CO",
    CODEISO3: "COL",
    CODENUM3: 170,
  },
  {
    COG: 99420,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Équateur",
    LIBENR: "République d'Équateur",
    CODEISO2: "EC",
    CODEISO3: "ECU",
    CODENUM3: 218,
  },
  {
    COG: 99421,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Paraguay",
    LIBENR: "République du Paraguay",
    CODEISO2: "PY",
    CODEISO3: "PRY",
    CODENUM3: 600,
  },
  {
    COG: 99422,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Pérou",
    LIBENR: "République du Pérou",
    CODEISO2: "PE",
    CODEISO3: "PER",
    CODENUM3: 604,
  },
  {
    COG: 99423,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Uruguay",
    LIBENR: "République orientale de l'Uruguay",
    CODEISO2: "UY",
    CODEISO3: "URY",
    CODENUM3: 858,
  },
  {
    COG: 99424,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Vénézuéla",
    LIBENR: "République bolivarienne du Vénézuéla",
    CODEISO2: "VE",
    CODEISO3: "VEN",
    CODENUM3: 862,
  },
  {
    COG: 99425,
    ACTUAL: 4,
    CRPAY: 99132,
    ANI: "",
    LIBCOG: "Territoires britanniques dans les Antilles et Bermudes",
    LIBENR:
      "Îles Turks-et-Caïcos ,  îles Caïmans , Montserrat , Anguilla , îles Vierges britanniques ,  Bermudes",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99426,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Jamaïque",
    LIBENR: "Jamaïque",
    CODEISO2: "JM",
    CODEISO3: "JAM",
    CODENUM3: 388,
  },
  {
    COG: 99427,
    ACTUAL: 4,
    CRPAY: 99132,
    ANI: "",
    LIBCOG: "Territoires britanniques dans l’océan Atlantique Sud",
    LIBENR:
      "Îles Malouines , territoire antarctique britannique , Géorgie-du-Sud-et-les-îles-Sandwich-du-Sud",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99428,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Guyana",
    LIBENR: "République coopérative du Guyana",
    CODEISO2: "GY",
    CODEISO3: "GUY",
    CODENUM3: 328,
  },
  {
    COG: 99429,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Bélize",
    LIBENR: "Bélize",
    CODEISO2: "BZ",
    CODEISO3: "BLZ",
    CODENUM3: "084",
  },
  {
    COG: 99430,
    ACTUAL: 4,
    CRPAY: 99101,
    ANI: "",
    LIBCOG: "Groenland",
    LIBENR: "Groenland",
    CODEISO2: "GL",
    CODEISO3: "GRL",
    CODENUM3: 304,
  },
  {
    COG: 99431,
    ACTUAL: 4,
    CRPAY: 99135,
    ANI: "",
    LIBCOG: "Aruba",
    LIBENR: "Aruba",
    CODEISO2: "AW",
    CODEISO3: "ABW",
    CODENUM3: 533,
  },
  {
    COG: 99432,
    ACTUAL: 4,
    CRPAY: 99404,
    ANI: "",
    LIBCOG: "Territoires des États-Unis en Amérique",
    LIBENR: "Porto Rico , îles Vierges des États-Unis",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99433,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1962,
    LIBCOG: "Trinité-et-Tobago",
    LIBENR: "République de Trinité-et-Tobago",
    CODEISO2: "TT",
    CODEISO3: "TTO",
    CODENUM3: 780,
  },
  {
    COG: 99434,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1966,
    LIBCOG: "Barbade",
    LIBENR: "Barbade",
    CODEISO2: "BB",
    CODEISO3: "BRB",
    CODENUM3: "052",
  },
  {
    COG: 99435,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1974,
    LIBCOG: "Grenade",
    LIBENR: "Grenade",
    CODEISO2: "GD",
    CODEISO3: "GRD",
    CODENUM3: 308,
  },
  {
    COG: 99436,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1973,
    LIBCOG: "Bahamas",
    LIBENR: "Commonwealth des Bahamas",
    CODEISO2: "BS",
    CODEISO3: "BHS",
    CODENUM3: "044",
  },
  {
    COG: 99437,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1975,
    LIBCOG: "Suriname",
    LIBENR: "République du Suriname",
    CODEISO2: "SR",
    CODEISO3: "SUR",
    CODENUM3: 740,
  },
  {
    COG: 99438,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1978,
    LIBCOG: "Dominique",
    LIBENR: "Commonwealth de Dominique",
    CODEISO2: "DM",
    CODEISO3: "DMA",
    CODENUM3: 212,
  },
  {
    COG: 99439,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1979,
    LIBCOG: "Sainte-Lucie",
    LIBENR: "Sainte-Lucie",
    CODEISO2: "LC",
    CODEISO3: "LCA",
    CODENUM3: 662,
  },
  {
    COG: 99440,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1979,
    LIBCOG: "Saint-Vincent-et-les-Grenadines",
    LIBENR: "Saint-Vincent-et-les-Grenadines",
    CODEISO2: "VC",
    CODEISO3: "VCT",
    CODENUM3: 670,
  },
  {
    COG: 99441,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1981,
    LIBCOG: "Antigua-et-Barbuda",
    LIBENR: "Antigua-et-Barbuda",
    CODEISO2: "AG",
    CODEISO3: "ATG",
    CODENUM3: "028",
  },
  {
    COG: 99442,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1983,
    LIBCOG: "Saint-Christophe-et-Niévès",
    LIBENR: "Fédération de Saint-Christophe-et-Niévès",
    CODEISO2: "KN",
    CODEISO3: "KNA",
    CODENUM3: 659,
  },
  {
    COG: 99443,
    ACTUAL: 4,
    CRPAY: 99135,
    ANI: 2010,
    LIBCOG: "Bonaire, Saint-Eustache, Saba",
    LIBENR: "Bonaire, Saint-Eustache, Saba",
    CODEISO2: "BQ",
    CODEISO3: "BES",
    CODENUM3: 535,
  },
  {
    COG: 99444,
    ACTUAL: 4,
    CRPAY: 99135,
    ANI: 2010,
    LIBCOG: "Curaçao",
    LIBENR: "Curaçao",
    CODEISO2: "CW",
    CODEISO3: "CUW",
    CODENUM3: 531,
  },
  {
    COG: 99445,
    ACTUAL: 4,
    CRPAY: 99135,
    ANI: 2010,
    LIBCOG: "Saint-Martin (partie néerlandaise)",
    LIBENR: "Saint-Martin (partie néerlandaise)",
    CODEISO2: "SX",
    CODEISO3: "SXM",
    CODENUM3: 534,
  },
  {
    COG: 99446,
    ACTUAL: 4,
    CRPAY: 99415,
    ANI: "",
    LIBCOG: "Antarctique argentin",
    LIBENR: "Antarctique argentin",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99447,
    ACTUAL: 4,
    CRPAY: 99417,
    ANI: "",
    LIBCOG: "Territoire chilien de l'Antarctique",
    LIBENR: "Territoire chilien de l'Antarctique",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99501,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Australie",
    LIBENR: "Commonwealth d'Australie",
    CODEISO2: "AU",
    CODEISO3: "AUS",
    CODENUM3: "036",
  },
  {
    COG: 99502,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Nouvelle-Zélande",
    LIBENR: "Nouvelle-Zélande",
    CODEISO2: "NZ",
    CODEISO3: "NZL",
    CODENUM3: 554,
  },
  {
    COG: 99503,
    ACTUAL: 4,
    CRPAY: 99132,
    ANI: "",
    LIBCOG: "Pitcairn",
    LIBENR: "Pitcairn",
    CODEISO2: "PN",
    CODEISO3: "PCN",
    CODENUM3: 612,
  },
  {
    COG: 99505,
    ACTUAL: 4,
    CRPAY: 99404,
    ANI: "",
    LIBCOG: "Territoires des États-Unis en Océanie",
    LIBENR:
      "Îles Mariannes du Nord, Guam, îles Samoa américaines, îles mineures éloignées des États-Unis",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99506,
    ACTUAL: 1,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Samoa",
    LIBENR: "État indépendant des Samoa",
    CODEISO2: "WS",
    CODEISO3: "WSM",
    CODENUM3: 882,
  },
  {
    COG: 99507,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1968,
    LIBCOG: "Nauru",
    LIBENR: "République de Nauru",
    CODEISO2: "NR",
    CODEISO3: "NRU",
    CODENUM3: 520,
  },
  {
    COG: 99508,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1970,
    LIBCOG: "Fidji",
    LIBENR: "République des Fidji",
    CODEISO2: "FJ",
    CODEISO3: "FJI",
    CODENUM3: 242,
  },
  {
    COG: 99509,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1970,
    LIBCOG: "Tonga",
    LIBENR: "Royaume des Tonga",
    CODEISO2: "TO",
    CODEISO3: "TON",
    CODENUM3: 776,
  },
  {
    COG: 99510,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1975,
    LIBCOG: "Papouasie-Nouvelle-Guinée",
    LIBENR: "État indépendant de Papouasie-Nouvelle-Guinée",
    CODEISO2: "PG",
    CODEISO3: "PNG",
    CODENUM3: 598,
  },
  {
    COG: 99511,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1978,
    LIBCOG: "Tuvalu",
    LIBENR: "Tuvalu",
    CODEISO2: "TV",
    CODEISO3: "TUV",
    CODENUM3: 798,
  },
  {
    COG: 99512,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1978,
    LIBCOG: "Salomon",
    LIBENR: "Îles Salomon",
    CODEISO2: "SB",
    CODEISO3: "SLB",
    CODENUM3: "090",
  },
  {
    COG: 99513,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1979,
    LIBCOG: "Kiribati",
    LIBENR: "République des Kiribati",
    CODEISO2: "KI",
    CODEISO3: "KIR",
    CODENUM3: 296,
  },
  {
    COG: 99514,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1980,
    LIBCOG: "Vanuatu",
    LIBENR: "République du Vanuatu",
    CODEISO2: "VU",
    CODEISO3: "VUT",
    CODENUM3: 548,
  },
  {
    COG: 99515,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1990,
    LIBCOG: "Marshall",
    LIBENR: "République des îles Marshall",
    CODEISO2: "MH",
    CODEISO3: "MHL",
    CODENUM3: 584,
  },
  {
    COG: 99516,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1990,
    LIBCOG: "Micronésie",
    LIBENR: "États fédérés de Micronésie",
    CODEISO2: "FM",
    CODEISO3: "FSM",
    CODENUM3: 583,
  },
  {
    COG: 99517,
    ACTUAL: 1,
    CRPAY: "",
    ANI: 1994,
    LIBCOG: "Palaos",
    LIBENR: "République des Palaos",
    CODEISO2: "PW",
    CODEISO3: "PLW",
    CODENUM3: 585,
  },
  {
    COG: 99519,
    ACTUAL: 4,
    CRPAY: 99502,
    ANI: "",
    LIBCOG: "Territoires de la Nouvelle-Zélande",
    LIBENR: "Tokelau , dépendance de Ross",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99520,
    ACTUAL: 4,
    CRPAY: 99502,
    ANI: 1965,
    LIBCOG: "Cook",
    LIBENR: "Îles Cook",
    CODEISO2: "CK",
    CODEISO3: "COK",
    CODENUM3: 184,
  },
  {
    COG: 99521,
    ACTUAL: 4,
    CRPAY: 99502,
    ANI: 1974,
    LIBCOG: "Niue",
    LIBENR: "Niue",
    CODEISO2: "NU",
    CODEISO3: "NIU",
    CODENUM3: 570,
  },
  {
    COG: 99522,
    ACTUAL: 4,
    CRPAY: 99501,
    ANI: "",
    LIBCOG: "Territoires de l’Australie en Océanie",
    LIBENR: "Île Norfolk , îles de la mer de Corail",
    CODEISO2: "",
    CODEISO3: "",
    CODENUM3: "",
  },
  {
    COG: 99699,
    ACTUAL: 4,
    CRPAY: "",
    ANI: "",
    LIBCOG: "Antarctique",
    LIBENR: "Antarctique",
    CODEISO2: "AQ",
    CODEISO3: "ATA",
    CODENUM3: "010",
  },
];
