name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main
    paths:
        - frontend/**
        - docker/**
        - .github/workflows/deploy-frontend.yml

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: . # Set the working directory to 'frontend'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove root ESLint config
        working-directory: ./
        run: rm .eslintrc.json

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Adjust Node.js version as needed

      - name: Install dependencies with Yarn
        working-directory: ./frontend
        run: yarn install

      - name: Build project
        working-directory: ./frontend
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          rm src/config/environment.ts; cp src/config/environment.ts.prod src/config/environment.ts
          yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3 # Update to your AWS region

      - name: Sync built files to S3
        working-directory: ./frontend
        run: |
          aws s3 sync ./build s3://linventaire-app --delete
        env:
          S3_BUCKET: linventaire-app

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
        env:
          DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
